name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge-job:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]' # Only run for Dependabot PRs

    steps:
      - uses: actions/checkout@v4

      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge Dependabot PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          RUN_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.DEPENDABOT_TOKEN}}
        run: |
          # Approve the PR
          gh pr review --approve -b 'Auto approved by auto-merge workflow' "$PR_URL"
          # Merge the PR
          export GH_TOKEN=$RUN_TOKEN
          gh pr merge --auto --merge "$PR_URL"
